/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyComplaintsRouteImport } from './routes/my-complaints'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ReportRouteImport } from './routes/report'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAlgorithmsRouteImport } from './routes/admin.algorithms'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminDuplicatesRouteImport } from './routes/admin.duplicates'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminSlaRouteImport } from './routes/admin.sla'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as ComplaintIdRouteImport } from './routes/complaint.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyComplaintsRoute = MyComplaintsRouteImport.update({
  id: '/my-complaints',
  path: '/my-complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlgorithmsRoute = AdminAlgorithmsRouteImport.update({
  id: '/admin/algorithms',
  path: '/admin/algorithms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/admin/complaints',
  path: '/admin/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDuplicatesRoute = AdminDuplicatesRouteImport.update({
  id: '/admin/duplicates',
  path: '/admin/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/admin/map',
  path: '/admin/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlaRoute = AdminSlaRouteImport.update({
  id: '/admin/sla',
  path: '/admin/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintIdRoute = ComplaintIdRouteImport.update({
  id: '/complaint/$id',
  path: '/complaint/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-complaints': typeof MyComplaintsRoute
  '/notifications': typeof NotificationsRoute
  '/report': typeof ReportRoute
  '/staff': typeof StaffRoute
  '/admin/algorithms': typeof AdminAlgorithmsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/sla': typeof AdminSlaRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/complaint/$id': typeof ComplaintIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-complaints': typeof MyComplaintsRoute
  '/notifications': typeof NotificationsRoute
  '/report': typeof ReportRoute
  '/staff': typeof StaffRoute
  '/admin/algorithms': typeof AdminAlgorithmsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/sla': typeof AdminSlaRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/complaint/$id': typeof ComplaintIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-complaints': typeof MyComplaintsRoute
  '/notifications': typeof NotificationsRoute
  '/report': typeof ReportRoute
  '/staff': typeof StaffRoute
  '/admin/algorithms': typeof AdminAlgorithmsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/sla': typeof AdminSlaRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/complaint/$id': typeof ComplaintIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/my-complaints'
    | '/notifications'
    | '/report'
    | '/staff'
    | '/admin/algorithms'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/duplicates'
    | '/admin/map'
    | '/admin/sla'
    | '/admin/staff'
    | '/admin/verification'
    | '/complaint/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/my-complaints'
    | '/notifications'
    | '/report'
    | '/staff'
    | '/admin/algorithms'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/duplicates'
    | '/admin/map'
    | '/admin/sla'
    | '/admin/staff'
    | '/admin/verification'
    | '/complaint/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/my-complaints'
    | '/notifications'
    | '/report'
    | '/staff'
    | '/admin/algorithms'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/duplicates'
    | '/admin/map'
    | '/admin/sla'
    | '/admin/staff'
    | '/admin/verification'
    | '/complaint/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyComplaintsRoute: typeof MyComplaintsRoute
  NotificationsRoute: typeof NotificationsRoute
  ReportRoute: typeof ReportRoute
  StaffRoute: typeof StaffRoute
  AdminAlgorithmsRoute: typeof AdminAlgorithmsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminDuplicatesRoute: typeof AdminDuplicatesRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminSlaRoute: typeof AdminSlaRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  ComplaintIdRoute: typeof ComplaintIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-complaints': {
      id: '/my-complaints'
      path: '/my-complaints'
      fullPath: '/my-complaints'
      preLoaderRoute: typeof MyComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/algorithms': {
      id: '/admin/algorithms'
      path: '/admin/algorithms'
      fullPath: '/admin/algorithms'
      preLoaderRoute: typeof AdminAlgorithmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/admin/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/duplicates': {
      id: '/admin/duplicates'
      path: '/admin/duplicates'
      fullPath: '/admin/duplicates'
      preLoaderRoute: typeof AdminDuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/admin/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sla': {
      id: '/admin/sla'
      path: '/admin/sla'
      fullPath: '/admin/sla'
      preLoaderRoute: typeof AdminSlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint/$id': {
      id: '/complaint/$id'
      path: '/complaint/$id'
      fullPath: '/complaint/$id'
      preLoaderRoute: typeof ComplaintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyComplaintsRoute: MyComplaintsRoute,
  NotificationsRoute: NotificationsRoute,
  ReportRoute: ReportRoute,
  StaffRoute: StaffRoute,
  AdminAlgorithmsRoute: AdminAlgorithmsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminDuplicatesRoute: AdminDuplicatesRoute,
  AdminMapRoute: AdminMapRoute,
  AdminSlaRoute: AdminSlaRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  ComplaintIdRoute: ComplaintIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
